# fly.toml app configuration file generated for myapp-xq4gaa on 2024-12-14T08:57:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'myapp-xq4gaa'
primary_region = 'sea'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
